Correctly report indices and aliases
toptal/chewy pull request #757
Opened 2021-02-11 17:18 UTC by dalthon

Just a rebased version of https://github.com/toptal/chewy/pull/689

2021-02-11 17:40 UTC, rabotyaga requested changes
What will happen, if we will have `UsersIndex` & `UsersActivitiesIndex`?

2021-02-11 18:00 UTC, dalthon commented
@rabotyaga as you guessed correctly it breaks... let me check if I can quickly solve this, otherwise I think it might be good to close this PR

2021-02-11 19:58 UTC, dalthon commented
@rabotyaga unfortunately we have to rely on something other than name prefix to associate Index class and indexes. This may be done by aliases or perfect name match.

Not every cases are covered, at https://github.com/toptal/chewy/blob/7edd7ae7656758d6cbd66122978680470e952dd5/spec/chewy/index/actions_spec.rb#L64 and https://github.com/toptal/chewy/blob/7edd7ae7656758d6cbd66122978680470e952dd5/spec/chewy/index/actions_spec.rb#L123 I highlighted cases where, due to the lack of alias, we can't map all indexes.

But I believe that is better to have false positives than false negatives in that unlikely case.

WDYT?

2021-02-12 17:57 UTC, rabotyaga approved these changes

2021-02-15 07:36 UTC, barthez approved these changes

2021-02-15 07:52 UTC, merged